#!/bin/bash

TIKZFILES="cubic_hierarchy triang_hierarchy"
cd img/
for file in $TIKZFILES ; do
	pdflatex -interaction=nonstopmode "$file.tikz"
done
./numerics.py
./sbplots.py

cd ..
latexmk -pdf -pv -f thesis.tex
